#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Linux-NBD
version:      0.22
version_from: lib/Linux/NBD.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.10_07
